#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Sensor, dgtl5,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  leftEncoder,         sensorQuadEncoder)
#include "constants.h"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*    This program drives forward for 0.5 meters then backwards, then increments the length by 0.5    *|
|*    until it has driven 2.5 meters forward then backwards                                           *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 9        leftMotor           VEX 3-wire module     Left side motor                   *|
|*		Sensor Port 15      rightEncoder 															Right side encoder								*|
|*    Sensor Port 17      leftEncoder 															Left side encoder	   							*|
\*-----------------------------------------------------------------------------------------------4246-*/

string turnList[3] = {"l", "r", "r"};

void driveForward(int rot) {
	while (SensorValue(rightEncoder) < rot) {
		if(SensorValue[rightEncoder] == -SensorValue[leftEncoder]) {
			motor[rightMotor] = 70;
			motor[leftMotor]  = 70;
		}
		else if(SensorValue[rightEncoder] > -SensorValue[leftEncoder])
		{
			motor[rightMotor] = 50;
			motor[leftMotor]  = 70;
		}
		else
		{
			motor[rightMotor] = 70;
			motor[leftMotor]  = 50;
		}
	}
}

void clearSensors() {
  SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
}

void stopMotors(int tim) {
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(tim);
}

void turnLeft() {
	while (SensorValue(rightEncoder) < 90 * 3) {
		motor[rightMotor] = 50;
		motor[leftMotor] = -50;
	}
}

void turnRight() {
	while (-SensorValue(leftEncoder) < 90 * 3.8) {
		motor[leftMotor] = 50;
		motor[rightMotor] = -50;
	}
}

task main()
{
	for (int i = 0; i < 3; i++) {
		clearSensors();
		driveForward(0.5*BASEROTATION);
		clearSensors();
		if (turnList[i] == "l") {
			turnLeft();
		} else {
			turnRight();
		}
		clearSensors();
		driveForward(0.5*BASEROTATION);
		stopMotors(250);
	}
}
