#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#include "constants.h"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*    This program drives forward for 0.5 meters then backwards, then increments the length by 0.5    *|
|*    until it has driven 2.5 meters forward then backwards                                           *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 9        leftMotor           VEX 3-wire module     Left side motor                   *|
|*		Sensor Port
\*-----------------------------------------------------------------------------------------------4246-*/


const int TIMECONST = 2247;
bool l = true;
float length = 0.5;
void driveForward(int len) {
	motor[rightMotor] = 127;
	motor[leftMotor]  = 70;
	wait1Msec(len);
}

void driveBackward(int len) {
	motor[rightMotor] = -75;
	motor[leftMotor]  = -127;
	wait1Msec(len);
}

void stopMotors(int tim) {
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(tim);
}
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main() {
	while (l) {
		if (length == 2.5) {
			l = false;
		}
		driveForward(length*TIMECONST);
		stopMotors(250);
		driveBackward(length*TIMECONST);
		stopMotors(250);
		length = length + 0.5;
		writeDebugStream("length: %d and length*time: %d", length, length*TIMECONST);
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
