#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Sensor, dgtl5,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  leftEncoder,         sensorQuadEncoder)
#include "constants.h"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*    This program drives forward for 0.5 meters then backwards, then increments the length by 0.5    *|
|*    until it has driven 2.5 meters forward then backwards                                           *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 9        leftMotor           VEX 3-wire module     Left side motor                   *|
|*		Sensor Port
\*-----------------------------------------------------------------------------------------------4246-*/

bool l = true;
float length = 0.5;

/*
void driveForward(int rot) {
	while (SensorValue(rightEncoder) < rot) {
		motor[rightMotor] = 127;
		motor[leftMotor]  = 70;
	}
}

void driveBackward(int rot) {
	while (SensorValue(leftEncoder) < rot) {
		motor[rightMotor] = -65;
		motor[leftMotor]  = -115;
	}
}
*/

void driveForward(int rot) {
	while (SensorValue(rightEncoder) < rot) {
		if(SensorValue[rightEncoder] == -SensorValue[leftEncoder]) {
			motor[rightMotor] = 90;
			motor[leftMotor]  = 90;
		}
		else if(SensorValue[rightEncoder] > -SensorValue[leftEncoder])
		{
			motor[rightMotor] = 70;
			motor[leftMotor]  = 90;
		}
		else
		{
			motor[rightMotor] = 90;
			motor[leftMotor]  = 70;
		}
	}
}

void driveBackward(int rot) {
	while (SensorValue(leftEncoder) < rot) {
		if(SensorValue[leftEncoder] == -SensorValue[rightEncoder]) {
			motor[rightMotor] = -90;
			motor[leftMotor]  = -90;
		}
		else if(SensorValue[leftEncoder] > -SensorValue[rightEncoder])
		{
			motor[rightMotor] = -70;
			motor[leftMotor]  = -90;
		}
		else
		{
			motor[rightMotor] = -90;
			motor[leftMotor]  = -70;
		}
	}
}

void clearSensors() {
  SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
}

void stopMotors(int tim) {
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(tim);
}
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main() {
	while (l) {
		if (length == 2.5) {
			l = false;
		}
		clearSensors();
		int rotLength = length*BASEROTATION;
		driveForward(rotLength);
		clearSensors();
		stopMotors(500);
		driveBackward(rotLength);
		stopMotors(500);
		length = length + 0.5;
		writeDebugStream("length: %d and length*time: %d", length, length*BASETIME);
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
