#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "foll/controlsVoid.c"

/*----------------------------------------------------------------------------------------------------*\
|*                                     - Dual Joystick Control -                                      *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program allows the robot to be controlled by a controller. The claw is controlled with 4     *|
|*  buttons and the motors are controlled by the right joystick.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Right joystick controls both the left and right motor.                                      *|
|*    2)  The claw is controlled by buttons 7L and 7D and arm by buttons 8R and 8D                    *|
|*    3)  Pressing 7U stops the program                                                               *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 6          clawMotor            VEX Motor           Claw motor                     *|
|*    Motor - Port 7					armMotor						 VEX motor					 Arm motor											*|
|*    Motor - Port 9          leftMotor            VEX motor           leftMotor                      *|
\*----------------------------------------------------------------------------------------------------*/



//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
  while(true)
  {
  	if (vexRT[Btn7U] == 1) {
  		break;
  	}
  	enableControls();
  }

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
